language: java
jdk: oraclejdk8
install: true
script: mvn clean install -DskipTests=true
services:
- docker
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=latest
- export IMAGE_NAME=shwetabh3955/ezzzy_backendservices
- docker build -t $IMAGE_NAME .
- docker tag $IMAGE_NAME $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
deploy:
  provider: heroku
  app: ezzzy-backendservices
  api_key:
    secure: fRn84f+hGbrMi/cGZZTZwRY4GmrCp+kOmc8XJ8BtfjiVtgttaTIVmcSb0kn+J8RY0q0cyNIRLlYxXBrj8aLtivej0D3xhw08dGgsFg0lbA/xQKLTJl61KCjn3G0fKbAwpHdYy1Ixdy91wlcDskGc37opiGCVOU3vz6eEb4arqtyQLOYFV9tiSoRy6ME5EyN/qEEMK2bye5+//jhtrAXve/aiWIauPyXSDIxpHItd3BlnMbsGtBVF9l7jz9+O+HWg4l55kgQnIwiMhWlJnEEbSxJTvf8B6vefuBaC9lc6Q/MBUin9/mKw/eIDrb2WrqYjlBx6FkNFNye3HbZqwsTkEUm2w6ifIsg9M4IC7AG2sY+QBU+0mHJTjiG2FO3SwlKPJja0NMYshol6Kp3/WAj7ZB7dXa5V7h9zEfuiMc43jCkor+9NQQdRqK9LCYZltgK4ZUx5niMcXB4FRWuc3jVeGmsS2R4MqxjjgI+PSPmp+j/A/G116PBruCudT+2v29qZiarXS2ym1xlcaGptFB+0ENpaQGJI660oLpCtAtUaEfc7/NcjEiluGynq2RFHRQSrSuN8Tai7WXy0mfd0gaZLS5mreRuCkG2kXykPe8cZiC3HUWxiQRrsQwOBBwTFq650ecmTimdurDnu80Yi7FR3njnYKkjN3IEz6jJ0YoyaIoQ=
