language: java
jdk: oraclejdk8
install: true
script: mvn clean install -DskipTests=true
services:
- docker
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=latest
- export IMAGE_NAME=shwetabh3955/ezzzy_backendservices
- docker build -t $IMAGE_NAME .
- docker tag $IMAGE_NAME $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
deploy:
  provider: heroku
  api_key:
    secure: E972hXbkrV6Ug2NTNqZL2ymPLs1UWuH7h2MQg8LEOrgh6XXDQz5UC+iOpV0gbHYrAEkyNMSzGSuz1n+9fI0yFL+bWFtT9SY9AI/hPi98DTGSMVUkYZ0cpZkbvr+n62aQ/MACl+U/U2Dxa8JebQro8v+HgXdMNQR5TpMQYXqPSNkGO8k14TNdGjKjWy+Ph/8RMsFBXtp8tU23xmgXdfsNFdNG+iK2Seov5PRFehXZYaImyvR7f6yzOnAAcq4amRIK+D+oj0+hDfN2V5QgIfOAlZXJgPRnwW3lcevfeSVAhGbLJgJkPADunMO5Yz8HbrpVEMe/rdtycq7AYeNFfePRyQK9TKCjzdX/FXoIcdxZ4JcRoVIgtZVBJScIi3WRKfbslgoKHa0dnyUDLq0Jl+yj1zMjuM+aIfPN/g9MFO272HuOpdJlYgHFTSkLpOWxMAXNrlAonCudu1Arf7r0IZclIal3F9Sd2zDOsnNMR4DiGXp75csLgvfYBXyeFVQe2rpGBcG2R5j/3OXzLz0lmDix2/5O3qownttvpdSfoZ+aPwqcesA8xoFvnsgyJx9OnTYjHL/FB5Al2+ToiZDxU9cuy7X31zt5ZsnRkBAGT89fbQM4IbO5FYfeCI5w5tslMZXUBzAxFg6lQ7rLfXnCOhRObutpCw6WUwb0wxpQTOWeN44=
  app: ezzzy-backendservices
