language: java
jdk: oraclejdk8
install: true
script: mvn clean install -DskipTests=true
services:
- docker
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=latest
- export IMAGE_NAME=shwetabh3955/ezzzy_backendservices
- docker build -t $IMAGE_NAME .
- docker tag $IMAGE_NAME $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
env:
  global:
  - secure: aeUPVCxbeZz/pxn2246/jwbXeDjtN2pwfkY4sZ4Yq6vl+kuYgeOhrFYLh+psryLr5BGMCVQ0RspSDXVoR6N5N29y1F474+XY98qvAMHhAzPmfff73sBDFwXZBGkkB3KyRwg0CirOCpfYWjbJG7Xe4gHEqccP96E3vuMCncLeVsnhhtpFCuZerz44d7tYp6UCm+rPcrpsq4pEbNqTJEE0BbDsR32DM+fXlRHqUo5xreu1zCDFrtXoSP3Z5SDXNfasV4hC9e2dQez3miPGYfRbyJpwCdOxiHgK41VJ+4e6TP5ZDVtCywRzjVTFx4q1GdNmo6jKKqYC7BK10ft9DOndBmEK1rGF/bID+ENokcSj3SV/vjc7hyRgBCgLLRtlFESYNA2KzMIR4e+EMv8wGCzi/vnTdY4XFahhv0U0pDWZP42rOfbzINPWzm6jNGH1Hv8WPuLg9yATl9vB8rC+ytYz/fi0Scf4vZ8OADr3mgXuwTOMLmdvaxJi6599k6jeSsMCXRfrspC8QZNw2UftQbhsX7Jf+4p9H1bRrmQeipfiW5NPW7yzcUsOdmiuRArX3Bn6xfCsKb0l/p3DP4le7Rb/l4PhPQMwH7eEq8oMHCFWFfo704mgOKHpdhokkwPkj6IjZ0U2VRVh89mAzpy6cJN4zahaqU+t18H9gVRTtFouP4o=
  - secure: YGNZEF60iU06EExTn4s9L2auVwKBdcyjeCLhiS+ABtBE+UE+yIPRLJMIKT1W2PdLQp1HmMntyzbNdtBropPsTzGMccaSR2Cv/y/toUvG3TfMCsYeRAqOK09AD/mjE5sNImnys3tZhbOQjNKJxOCzZUBtadTXCTR+xyeN8LGjBbBD9o9HH5ACuA0tOw8Hl0QvA6DD2eIDNWcREXVv4GRSC41cXxe61U+qlPr1N87LK54drhYJH4NLNAs1kXfwSCpcsCZPxXRPBXlRIC3lFNa0Z9xz1SxdcC3PhSrCF4idwFneflmck4CeUsnuOYwDi9vdhE8gzfGz3ecko8ckCdlxbzkVHZhP1/KDVD2C6KX7iUPaKTH7o8SkZv/D6J/lD5YLSjpMkHrFd4r7xNRuhhm01hQecs0wBhNO+dZTZ2ILtRQplUgjBsHszEWxv33Ipmr5oBGsh8dazOgME8Z+ZPK9iGDhW8Y2Vgl+Fu8myK5UtBIWb89bGc2P1SFO0in+M6yeWvfS1depOy5QPb6McZXmgCGY1ONS9CpuSYViqnsAD6Sgon2l9Sv+V1TTcRdjVabeaJdxlbZI3qwRu5KGrRl7MwRpa08E0oJVQkmwb2UydZRAOFhh7AbG38S5gzgsaMwEo5E1ftEv1j9d78zePVcJtsrvonRzRtoHk4yh26Gs4PE=
