variables:
  REVIEW_APP_NAME: "$CI_COMMIT_REF_SLUG-$CI_PROJECT_NAME"
  
stages:
  - build
  - review
  - deploy

build:
  stage: build
  image: maven:3.3.9-jdk-8
  script:
    - mvn clean package
  tags:
    - docker
    - shared


    
deploy_dev:
  stage: deploy
  image: ruby:2.3
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=vel-ci-api-dev --api-key=$HEROKU_API_KEY
  environment:
    name: dev
    url: https://vel-ci-api-dev.herokuapp.com
  only:
    - master
  tags:
    - docker
    - shared
    